#!/usr/bin/env bash
#
# Validation pipeline — pulls the HTML report generated by the in-cluster
# html_report stage back to the GitHub job so it can be uploaded as an artifact.
#
# The dispatched job writes the report into a ConfigMap before exiting (see
# scripts/ci/generate-report.sh); the pod itself is gone by the time this runs.

set -euo pipefail
# shellcheck source=scripts/lib/common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"

require_cmd kubectl
require_cmd terraform
require_cmd python3

CI_NAMESPACE="${CI_NAMESPACE:-ci-dispatch}"
COMMIT_SHA="${GITHUB_SHA:?GITHUB_SHA required}"
CONFIGMAP_NAME="validation-report-${COMMIT_SHA:0:8}"

terraform -chdir="${INFRA_DIR}" init -input=false -reconfigure \
  -backend-config="bucket=${TF_STATE_BUCKET}" \
  -backend-config="key=${PROJECT_NAME}/terraform.tfstate" \
  -backend-config="region=${AWS_REGION}" >/dev/null

ensure_kubeconfig

mkdir -p "${REPO_ROOT}/reports"

log "Fetching the validation report from ConfigMap ${CONFIGMAP_NAME}"
if ! kubectl -n "${CI_NAMESPACE}" get configmap "${CONFIGMAP_NAME}" >/dev/null 2>&1; then
  fail "the in-cluster stage did not publish ${CONFIGMAP_NAME}"
fi

kubectl -n "${CI_NAMESPACE}" get configmap "${CONFIGMAP_NAME}" -o json \
  > "${REPO_ROOT}/reports/.configmap.json"

CONFIGMAP_JSON="${REPO_ROOT}/reports/.configmap.json" \
REPORT_DIR="${REPO_ROOT}/reports" \
python3 - <<'PY'
import json
import os

with open(os.environ["CONFIGMAP_JSON"], "r", encoding="utf-8") as fh:
    payload = json.load(fh)

report_dir = os.environ["REPORT_DIR"]
data = payload.get("data") or {}
if not data:
    raise SystemExit("the report ConfigMap carried no data")

for filename, content in data.items():
    target = os.path.join(report_dir, filename)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"restored {target} ({len(content)} bytes)")
PY

rm -f "${REPO_ROOT}/reports/.configmap.json"

# The report has been captured as an artifact; the ConfigMap is transient state.
kubectl -n "${CI_NAMESPACE}" delete configmap "${CONFIGMAP_NAME}" --wait=false >/dev/null 2>&1 || true

log "Report retrieved"
ls -la "${REPO_ROOT}/reports"
